[env]
# gh-sync:keep-start
# Project-specific dependencies are listed here.

# gh-sync:keep-end

[tools]
"aqua:cli/cli" = "2.90.0"
"github:naa0yama/gh-sync" = "0.3.6"
actionlint = "1.7.12"
dprint = "0.54.0"
ghalint = "1.5.5"
usage = "3.2.1"
uv = "latest"
zizmor = "1.16.0"

[task_config]
includes = [
	".mise/tasks.toml",
	".mise/overrides.toml",
]
